### ISSUE TITLE
[1.17.1] Connected textures broken

### ISSUE THREAD

**Issue by prenetic** [yurisuika/Isabella#5]
Minecraft version: 1.17.1 Java
OptiFine version: HD U G9

When loading the 1.17 textures alongside the 1.17 models, connected textures are appearing incorrectly and behave one of two ways. So far I have noticed this with both window blocks and window panes, but I have not done extensive testing to determine all of the affected blocks.

If the models are loaded first (under the 1.17 textures in the resource pack list), then windows appear to have the following visual error:

<img width="1174" alt="modelsfirst" src="https://user-images.githubusercontent.com/11982895/131437645-e94d8f96-8b32-45b8-b086-34a697c277b7.png">

When loading the textures are loaded first, the following occurs:

<img width="1071" alt="texturesfirst" src="https://user-images.githubusercontent.com/11982895/131437653-ac8480c3-e926-4ba5-bc3e-e0e8f592db45.png">

When only loading the textures, behavior is as expected:

<img width="1125" alt="nomodels" src="https://user-images.githubusercontent.com/11982895/131437852-878ee6f3-63b2-4966-b76a-a10f927dcd88.png">

**Comment by yurisuika** [comment]
Hi, sorry for the late reply.

The model pack is the legacy remnants of what has not been added into the base packs yet. Eventually it will be removed, but it is considered obsolete.

The glass model is intended to override CTM; it has not been added in to the base pack yet because of exactly this (if my memory serves me correctly). However, I may do it eventually as part of detaching Isabella from OptiFine. Replacing CTM pumpkins with ones done with models is part of this philosophy, for example.

You should be loading the base pack first and the add-on packs afterwards; that is standard procedure. What you are experiencing is the CTM textures between the base and add-on pack changing. In the model pack, there are CTM textures for the glass designed to not break with having the model loaded and CTM at the same time. When you load the base second, you are getting the base CTM textures.
